FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . .

WORKDIR /src/PasswordManager.Client/

RUN /bin/bash -c 'dotnet restore'
RUN /bin/bash -c 'dotnet publish -c Debug -o /out'

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS dist

WORKDIR /app
COPY --from=build ./out .

EXPOSE 3000

ENTRYPOINT [ "dotnet", "PasswordManager.Client.dll" ]


# FROM mcr.microsoft.com/dotnet/sdk:7.0
# WORKDIR /app

# COPY . .

# ENTRYPOINT [ "bash" ]